-- Run this once in a Snowflake worksheet as ACCOUNTADMIN.
-- Creates a dedicated, least-privilege user/role for the app instead of
-- using ACCOUNTADMIN at runtime.

CREATE ROLE IF NOT EXISTS CENSUSSENSE_APP_ROLE;

CREATE WAREHOUSE IF NOT EXISTS CENSUSSENSE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE CENSUSSENSE_WH TO ROLE CENSUSSENSE_APP_ROLE;

-- Read-only access to the census database only.
GRANT IMPORTED PRIVILEGES ON DATABASE US_OPEN_CENSUS_DATA__NEIGHBORHOOD_INSIGHTS__FREE_DATASET
  TO ROLE CENSUSSENSE_APP_ROLE;

-- Dedicated app user. Replace the password before running, then put the
-- same value in .env as SNOWFLAKE_PASSWORD. Rotate it before sharing any
-- credentials externally.
CREATE USER IF NOT EXISTS CENSUSSENSE_APP_USER
  PASSWORD = 'REPLACE_WITH_STRONG_PASSWORD'
  DEFAULT_ROLE = CENSUSSENSE_APP_ROLE
  DEFAULT_WAREHOUSE = CENSUSSENSE_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE CENSUSSENSE_APP_ROLE TO USER CENSUSSENSE_APP_USER;
